# networks:
#     app_network:
#         driver: bridge

# services:
#     frontend:
#         build:
#             context: ./frontend
#             dockerfile: Dockerfile
#         container_name: frontend
#         ports:
#             - "5173:5173"
#         environment:
#             - NODE_ENV=development
#             - VITE_API_BASE_URL=http://localhost:8000/api/v1
#         depends_on:
#             - backend
#             - face_verification
#         networks:
#             - app_network

#     backend:
#         container_name: backend
#         image: node:18
#         ports:
#             - "8000:8000"
#         working_dir: /usr/src/app
#         volumes:
#             - ./backend:/usr/src/app
#         command: ["npm", "run", "dev"]
#         environment:
#             - PORT=8000
#             - MONGODB_URI=mongodb+srv://akashyadavbihari1:3IQrTRPHSjYJLcWI@iit-anandapur.wtsak.mongodb.net
#             - CORS_ORIGIN=http://localhost:5173
#             - ACCESS_TOKEN_SECRET=GEWACfe8aEIKdPwmoOIQ6PlJiKIKsdOit1psR2e9AbUkAHX3iKTV43g5jFXDKTBR
#             - ACCESS_TOKEN_EXPIRY=1d
#             - REFRESH_TOKEN_SECRET=Maus5k0bodODPAPFRF3Z7w4XjhcvtgxQVjsggi3DkxCYxdVjme5CZFLlv1TsOmQe
#             - REFRESH_TOKEN_EXPIRY=10d
#             - CLOUDINARY_CLOUD_NAME=cdakash
#             - CLOUDINARY_CLOUD_KEY=748159738588822
#             - CLOUDINARY_CLOUD_SECRET=d302vhJiCILmmWCT9V3XlRJp9oE
#             - OTP_KEY_PASS=lxtc peuz kjvk vcoj
#             - NODE_ENV=development
#             - BASE_URL=http://localhost:8000
#         networks:
#             - app_network

#     face_verification:
#         build:
#             context: ./face_verification
#             image: python:3.11-slim
#             ports:
#                 - "5000:5000"
#         container_name: face_verification
#         ports:
#             - "5000:5000"
#         depends_on:
#             - backend
#         networks:
#             - app_network

networks:
    app_network:
        driver: bridge

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        ports:
            - "5173:5173"
        environment:
            - NODE_ENV=development
            - VITE_API_BASE_URL=http://localhost:8000/api/v1
        depends_on:
            - backend
            - face_verification
        networks:
            - app_network

    backend:
        container_name: backend
        image: node:18
        ports:
            - "8000:8000"
        working_dir: /usr/src/app
        volumes:
            - ./backend:/usr/src/app
        command: >
            sh -c "
            npm install &&
            npm run dev
            "
        environment:
            - PORT=${PORT}
            - MONGODB_URI=${MONGODB_URI}
            - CORS_ORIGIN=http://localhost:5173
            - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
            - ACCESS_TOKEN_EXPIRY=1d
            - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
            - REFRESH_TOKEN_EXPIRY=10d
            - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
            - CLOUDINARY_CLOUD_KEY=${CLOUDINARY_CLOUD_KEY}
            - CLOUDINARY_CLOUD_SECRET=${CLOUDINARY_CLOUD_SECRET}
            - OTP_KEY_PASS=${OTP_KEY_PASS}
            - NODE_ENV=development
            - BASE_URL=http://localhost:8000
            - FEU=${FEU}
            - FVU=${FVU}
        networks:
            - app_network
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
            interval: 30s
            timeout: 10s
            retries: 3

    face_verification:
        build:
            context: ./face_verification
            dockerfile: Dockerfile
        container_name: face_verification
        ports:
            - "5000:5000"
        depends_on:
            - backend
        networks:
            - app_network
